#!/usr/bin/env python3
"""
Roni Pulse
Generate a deterministic GitHub repository health report.

The report intentionally avoids timestamps that change on every run.
That means GitHub Actions creates a commit only when real repository
metadata changes.
"""

from __future__ import annotations

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path


OUTPUT = Path("data/repo-health.md")
USERNAME = "webwithroni"


def gh_api(endpoint: str) -> list | dict:
    env = os.environ.copy()
    if "GH_TOKEN" not in env and "GITHUB_TOKEN" in env:
        env["GH_TOKEN"] = env["GITHUB_TOKEN"]

    result = subprocess.run(
        ["gh", "api", endpoint, "--paginate"],
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )

    raw = result.stdout.strip()

    # gh --paginate can concatenate JSON arrays. The endpoint used here is
    # normally a single JSON array, so handle both array and line-delimited
    # page output defensively.
    try:
        value = json.loads(raw)
        if isinstance(value, list):
            return value
        return value
    except json.JSONDecodeError:
        pages: list = []
        for line in raw.splitlines():
            line = line.strip()
            if not line:
                continue
            value = json.loads(line)
            if isinstance(value, list):
                pages.extend(value)
            else:
                pages.append(value)
        return pages


def fmt_date(value: str | None) -> str:
    if not value:
        return "—"
    try:
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d")
    except ValueError:
        return value[:10]


def main() -> None:
    repos = gh_api(
        f"users/{USERNAME}/repos"
        "?per_page=100&affiliation=owner&visibility=all"
        "&sort=pushed&direction=desc"
    )

    if not isinstance(repos, list):
        raise RuntimeError("Unexpected GitHub API response for repositories.")

    # Keep the output stable and compact.
    repos = sorted(
        repos,
        key=lambda r: (r.get("pushed_at") or "", r.get("name") or ""),
        reverse=True,
    )

    lines: list[str] = [
        "# ⚡ Roni Pulse",
        "",
        "> Auto-generated repository health snapshot for `webwithroni`.",
        "",
        f"**Repositories tracked:** {len(repos)}",
        "",
        "| Repository | Language | Stars | Forks | Open issues | Last push |",
        "|---|---|---:|---:|---:|---|",
    ]

    for repo in repos:
        name = repo.get("name", "unknown")
        url = repo.get("html_url", f"https://github.com/{USERNAME}/{name}")
        language = repo.get("language") or "—"
        stars = repo.get("stargazers_count", 0)
        forks = repo.get("forks_count", 0)
        issues = repo.get("open_issues_count", 0)
        pushed = fmt_date(repo.get("pushed_at"))

        lines.append(
            f"| [{name}]({url}) | {language} | {stars} | {forks} | "
            f"{issues} | {pushed} |"
        )

    lines.extend(
        [
            "",
            "---",
            "",
            "Generated by **Roni Pulse**.",
            "",
        ]
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
